### ISSUE TITLE
Content issue in the ansible.com page

### ISSUE THREAD

**Issue by mguetta1** [oVirt/ovirt-ansible-collection#55]
Hi, 
I was asked by Red Hat Customer Service to open the issue here. Hope it is indeed the right place.
I found a content issue in the Ansible module example here:
https://docs.ansible.com/ansible/latest/modules/ovirt_storage_vm_info_module.html#examples
The module used in the example should be: ovirt_storage_vm_info

**Comment by mnecas** [comment]
Hi,
yeah this is the right place the patch was already merged and I'll do backport to ansible 2.9
Thank you for the issue if you find other issues in oVirt Ansible modules don't hesitate to open the issue here.
Fix: https://github.com/oVirt/ovirt-ansible-collection/pull/53
Copy of: https://github.com/ansible-collections/community.general/issues/462

**Comment by mguetta1** [comment]
Thanks
